import type { DifyDsl, ValidationResult } from '@/shared/types/dsl'

function value(value: unknown): string {
  if (value === undefined || value === null || value === '')
    return '—'
  return typeof value === 'string' ? value : `\`${JSON.stringify(value)}\``
}

export function generateDocumentation(dsl: DifyDsl, validation: ValidationResult): string {
  const nodes = dsl.workflow?.graph.nodes ?? []
  const edges = dsl.workflow?.graph.edges ?? []
  const environments = dsl.workflow?.environment_variables ?? []
  const conversations = dsl.workflow?.conversation_variables ?? []
  const prompts = nodes.filter(node => node.data.type === 'llm')
  const dependencies = dsl.dependencies ?? []
  const errors = validation.issues.filter(issue => issue.severity === 'error')
  const warnings = validation.issues.filter(issue => issue.severity === 'warning')

  return `# ${dsl.app.name}

> Generated by Dify DSL Studio from DSL version ${dsl.version}.

## Overview

${dsl.app.description || 'No application description supplied.'}

- Mode: \`${dsl.app.mode}\`
- Nodes: ${nodes.length}
- Edges: ${edges.length}
- Validation: ${validation.valid ? 'valid' : 'requires attention'}
- Compatibility profile: Dify DSL 0.6.0

## Workflow

${nodes.map((node, index) => `${index + 1}. **${node.data.title || node.id}** — \`${node.data.type}\``).join('\n') || 'No executable workflow graph.'}

## Node catalog

| ID | Title | Type | Inputs / configuration |
|---|---|---|---|
${nodes.map(node => `| ${node.id} | ${node.data.title ?? '—'} | \`${node.data.type}\` | ${Object.keys(node.data).filter(key => !['title', 'type', 'selected'].includes(key)).join(', ') || '—'} |`).join('\n')}

## Variable catalog

### Environment variables

| Name | Type | Default | Secret |
|---|---|---|---|
${environments.map(variable => `| ${variable.name} | ${variable.value_type} | ${variable.value_type === 'secret' ? '[REDACTED]' : value(variable.value)} | ${variable.value_type === 'secret' ? 'yes' : 'no'} |`).join('\n') || '| — | — | — | — |'}

### Conversation variables

| Name | Type | Default |
|---|---|---|
${conversations.map(variable => `| ${variable.name} | ${variable.value_type} | ${value(variable.value)} |`).join('\n') || '| — | — | — |'}

## Prompt catalog

${prompts.map(node => `### ${node.data.title ?? node.id}\n\nProvider/model: ${value(node.data.model)}\n\nPrompt configuration is stored at \`workflow.graph.nodes[id=${node.id}].data.prompt_template\`.`).join('\n\n') || 'No LLM prompt nodes.'}

## Dependencies

${dependencies.map(dependency => `- \`${value(dependency)}\``).join('\n') || 'No plugin dependencies declared.'}

Knowledge-base IDs and workspace credentials are environment-specific. Dify may encrypt dataset IDs on export, and credential IDs are omitted unless secret-inclusive export is explicitly selected server-side.

## Error handling and approvals

${nodes.filter(node => node.data.error_strategy || node.data.type === 'human-input').map(node => `- ${node.data.title ?? node.id}: ${node.data.type === 'human-input' ? 'human input/approval gate' : `error strategy ${node.data.error_strategy}`}`).join('\n') || 'No explicit error strategies or human input nodes detected.'}

## Validation report

- Errors: ${errors.length}
- Warnings: ${warnings.length}

${[...errors, ...warnings].map(issue => `- **${issue.severity.toUpperCase()} ${issue.code}**: ${issue.message}${issue.path ? ` (\`${issue.path}\`)` : ''}`).join('\n') || 'No errors or warnings.'}

## Import and deployment

1. Review environment variables, model providers, plugins, tools, and knowledge-base mappings.
2. Import the YAML into a compatible Dify instance.
3. Resolve dependency and version confirmations presented by Dify.
4. Configure credentials inside Dify; do not embed secrets in DSL.
5. Test the draft workflow, then publish it.

## Test plan

- Parse and schema validation
- Graph reachability and edge integrity
- Variable lineage and template reference checks
- Golden path, empty input, invalid input, external dependency failure, timeout, and human rejection
- Export/import round-trip against the target Dify instance

## Limitations

Studio simulation does not execute code, tools, HTTP calls, retrieval, agents, or LLMs. These nodes use explicit mocks. Real execution requires approval and a configured Dify application API.

## Changelog

- ${new Date().toISOString().slice(0, 10)}: Documentation generated from the current project DSL.
`
}
